openapi: 3.0.0
info:
  $ref: ./info/index.yaml
servers:
  - url: 'http://localhost:3000'
    description: localhost
  - url: 'http://localhost:10083'
    description: Mock
  - url: 'http://petstore/v1'
    description: Production
tags:
  - name: Pet
  - name: User
paths:
  /api/v1/pets:
    post:
      summary: create
      operationId: create_pet
      description: ペットを登録する。
      tags:
        - Pet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 名称
                tag:
                  type: string
                  description: タグ
              required:
                - name
            example:
              name: 芝犬
              tag: 犬
      responses:
        '201':
          description: 'is expected to eq {"id"=>1, "name"=>"三毛猫", "tag"=>nil}'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  tag:
                    type: string
                    nullable: true
              example:
                id: 1
                name: 三毛猫
                tag: null
        '422':
          description: does not create a pet
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    items:
                      type: string
              example:
                name:
                  - has already been taken
    get:
      summary: index
      operationId: index_pets
      description: ペットを登録する。
      tags:
        - Pet
      responses:
        '200':
          description: 'is expected to eq [{"id"=>1, "name"=>"土佐犬", "tag"=>"Sunanda Devi"}, {"id"=>2, "name"=>"ペルシャ猫", "tag"=>"Nuptse"}]'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  nullable: true
                  properties:
                    id:
                      type: integer
                      description: ペットの id
                    name:
                      type: string
                      description: 名称
                    tag:
                      type: string
                      description: タグ
                  required:
                    - id
                    - name
              example:
                - id: 1
                  name: 土佐犬
                  tag: Sunanda Devi
                - id: 2
                  name: ペルシャ猫
                  tag: Nuptse
  '/api/v1/pets/{id}':
    get:
      summary: show
      operationId: show_pet
      description: ペットの情報を得る。
      tags:
        - Pet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 2
      responses:
        '200':
          description: 'is expected to eq {"id"=>2, "name"=>"ペルシャ猫", "tag"=>"Dhaulagiri IV"}'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ペットの id
                  name:
                    type: string
                    description: 名称
                  tag:
                    type: string
                    description: タグ
                required:
                  - id
                  - name
              example:
                id: 2
                name: ペルシャ猫
                tag: Dhaulagiri IV
        '404':
          description: 'is expected to eq {}'
          content:
            application/json:
              schema:
                type: object
                properties: {}
              example: {}
  /api/v1/users:
    post:
      summary: create
      operationId: create_user
      description: ユーザーを登録する。
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: ユーザー登録情報
              properties:
                username:
                  type: string
                  description: アカウント名
                password:
                  type: string
                  description: パスワード
                first_name:
                  type: string
                  description: 名前
                last_name:
                  type: string
                  description: 苗字
                email:
                  type: string
                  description: メールアドレス
                phone:
                  type: string
                  description: 電話番号
            example:
              username: johndoe
              password: ''
              first_name: ''
              last_name: ''
              email: john.doe@example.com
              phone: ''
      responses:
        '201':
          description: creates a user
          content:
            application/json:
              schema:
                type: object
                description: ユーザー登録情報
                properties:
                  id:
                    type: integer
                    description: ユーザー id
                  username:
                    type: string
                    description: アカウント名
                  first_name:
                    type: string
                    description: 名前
                  last_name:
                    type: string
                    description: 苗字
                  email:
                    type: string
                    description: メールアドレス
                  phone:
                    type: string
                    description: 電話番号
              example:
                id: 1
                username: johndoe
                first_name: John
                last_name: Doe
                email: john.doe@example.com
                phone: '0312345678'
        '422':
          description: does not create a user
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: array
                    items:
                      type: string
                  username:
                    type: array
                    items:
                      type: string
                  first_name:
                    type: array
                    items:
                      type: string
                  last_name:
                    type: array
                    items:
                      type: string
                  email:
                    type: array
                    items:
                      type: string
                  phone:
                    type: array
                    items:
                      type: string
              example:
                password:
                  - can't be blank
                  - is too short (minimum is 6 characters)
                username:
                  - has already been taken
                first_name:
                  - can't be blank
                last_name:
                  - can't be blank
                email:
                  - has already been taken
                phone:
                  - is invalid
                  - can't be blank
components:
  schemas:
    Pet:
      type: object
      description: ペットの詳細
      properties:
        id:
          type: integer
          format: int64
          description: ペットの id
        name:
          type: string
          description: 名称
        tag:
          type: string
          description: タグ
      required:
        - id
        - name
    Pets:
      type: array
      description: ペットの一覧 (id の昇順)
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      description: エラー情報
      properties:
        code:
          type: integer
          format: int32
          description: コード
        message:
          type: string
          description: メッセージ
      required:
        - code
        - message
